name: Project
description: Create an issue containing a new project idea
title: "[Project]: "
labels: ["project-backlog", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to write this project idea.

        Before creating a new project, please make sure that you are not creating a duplicate of another project. To do so, go to [Issues](https://github.com/pmgbergen/porepy/issues) and filter the issues using the tag `project-backlog`.

        If relevant, set asignees, labels, projects, and milestones on the right.

        We kindly ask you to fill out the following fields to create your new project idea.
  - type: textarea
    id: description
    attributes:
      label: Project description
      description: Please, provide a brief description of the project.
      placeholder: Brief description of the project.
    validations:
      required: true
  - type: dropdown
    id: compatibility
    attributes:
      label: Is backward compatible?
      description: Would the changes introduced by this project be backward-compatible with PorePy?
      options:
        - 'Yes'
        - 'No'
        - Not sure.
    validations:
      required: true
  - type: textarea
    id: backward_incompatible
    attributes:
      label: If backward-incompatible, what would be broken?
      description: If you answered *No* above. Please, comment which parts PorePy will break.
    validations:
      required: false
  - type: dropdown
    id: help_needed
    attributes:
      label: Type of user and amount of help
      description: Please provide the amount of help needed for this project.
      options:
        - I am a user, and I will work on my own.
        - I am a user, and I will need some help.
        - I am a core developer, and I will work on my own.
        - I am a core developer, and I will need some help.
    validations:
      requrired: true
  - type: dropdown
    id: implementation_length
    attributes:
      label: Implementation effort
      description: If possible, provide an estimate of the time-span of this project.
      options:
        - Hours.
        - Days.
        - Months.
    validations:
      required: false
  - type: dropdown
    id: user_project
    attributes:
      label: Would this make a good user meeting project?
      description: (For members of the organization only) Would this project be a good candidate for a user meeting project?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false
literal_block:
  - type: markdown
    attributes:
      value: |
        Hello