name: Project
description: Create an issue containing a new project idea
title: "[Project]: "
labels: ["project-backlog", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to write this project idea.

        Before creating a new project, please make sure that you are not creating a duplicate of another project. To do so, go to [Issues](https://github.com/pmgbergen/porepy/issues) and filter the issues using the tag `project-backlog`.

        Please, fill out the following fields to create your new project idea.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Plase, provide a brief description of the project.
      placeholder: Brief description of the project.
    validations:
      required: true
  - type: dropdown
    id: compatibility
    attributes:
      label: Compatibility
      description: Would the changes introduced by this project be backward-compatible with PorePy ?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: textarea
    id: backward_incompatible
    attributes:
      label: Backward-incompatible
      description: If you answered No above. Please, comment on which parts PorePy will break.
    validations:
      required: false
  - type: dropdown
    id: help
    attributes:
      label: Help
      description: Please provide the amount of help you will need for this project.
      options:
        - I can do it on my own.
        - I can do it on my own but with the help of a developer.
        - I cannot do this project alone, I will need some help.
    validations:
      requrired: true
  - type: dropdown
    id: implementation_length
    attributes:
      label: Implementation effort
      description: If possible, provide an estimate of the time-span of this project.
      options:
        - N/A.
        - Hours.
        - Days.
        - Months.
    validations:
      required: false
  - type: dropdown
    id: user_project
    attributes:
      label: User project
      description: (For members of the organization only) Would this project be a good candidate for a user meeting project?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Project task list

        This is the place where the project leader will track the progress of a project using [task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists).

        - [x] First task in the list.
        - [] Second task in the list.
        - [ ] And so on and so forth.