name: Project
description: Create an issue containing a new project idea
title: "[Project]: "
labels: ["project-backlog", "help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to write this project idea.

        Before creating a new project, please make sure that you are not creating
          a duplicate of another project. To do so, go to
          [Issues](https://github.com/pmgbergen/porepy/issues) and filter the issues
          using the tag `project-backlog`.

        Please, fill out the following fields to create your new project idea.
  - type: input
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the project
      placeholder: ex. email@example.com
    validations:
      required: false